version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo "master"
      - echo "$ENVIRONMENT_NAME"
      - echo Build started on `date`

      # Build images for different services
      - docker build -t $REPOSITORY_URI:web-service -f project/Dockerfile.web .
      - docker build -t $REPOSITORY_URI:worker-service -f project/Dockerfile.worker .
      - docker build -t $REPOSITORY_URI:dashboard-service -f project/Dockerfile.dashboard .

      # Tag images
      - docker tag $REPOSITORY_URI:web-service $REPOSITORY_URI:web-service-$IMAGE_TAG
      - docker tag $REPOSITORY_URI:web-service $REPOSITORY_URI:web-service-master
      - docker tag $REPOSITORY_URI:worker-service $REPOSITORY_URI:worker-service-$IMAGE_TAG
      - docker tag $REPOSITORY_URI:worker-service $REPOSITORY_URI:worker-service-master
      - docker tag $REPOSITORY_URI:dashboard-service $REPOSITORY_URI:dashboard-service-$IMAGE_TAG
      - docker tag $REPOSITORY_URI:dashboard-service $REPOSITORY_URI:dashboard-service-master
  post_build:
    commands:
      - echo Build completed on `date`

      # Push images to ECR
      - docker push $REPOSITORY_URI:worker-service
      - docker push $REPOSITORY_URI:dashboard-service
      - docker push $REPOSITORY_URI:web-service-$IMAGE_TAG
      - docker push $REPOSITORY_URI:worker-service-$IMAGE_TAG
      - docker push $REPOSITORY_URI:dashboard-service-$IMAGE_TAG
      - docker push $REPOSITORY_URI:web-service

      # Writing image definitions file
      - printf '[{"name":"%s","imageUri":"%s"}]' "web-task" "$REPOSITORY_URI:web-service-master" > imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s"}]' "worker-service" "$REPOSITORY_URI:worker-service-master" >> imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s"}]' "dashboard-service" "$REPOSITORY_URI:dashboard-service-master" >> imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
