version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - yum install docker -y
      - nohup dockerd &
      - export REPOSITORY_URI=235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Starting build phase..."
      - export REPOSITORY_URI="$REPOSITORY_URI"
      - docker-compose -f project/docker-compose.yml build
      - docker tag "project_web:latest" "$REPOSITORY_URI:$IMAGE_TAG"
      - docker tag "$REPOSITORY_URI:latest" "$REPOSITORY_URI:master"
      - docker images

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$REPOSITORY_URI"
      - docker-compose -f project/docker-compose.yml push

artifacts:
  files:
    - project/docker-compose.yml
    - imagedefinitions.json
