version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - apt-get update -y
      - apt-get install -y docker.io

  build:
    commands:
      - echo "Starting build phase..."
      - docker-compose -f project/docker-compose.yml build

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks
      - docker-compose -f project/docker-compose.yml push

artifacts:
  files: project/docker-compose.yml

