version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo "master"
      - echo "$ENVIRONMENT_NAME"
      - echo Build started on `date`

      # Build the single container image
      - docker build -t $REPOSITORY_URI:master -f project/Dockerfile .

      # Tag the image
      - docker tag $REPOSITORY_URI:master $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`

      # Push the image to ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:master

      # Writing image definitions file for each service
      - printf '[{"name":"web-task","imageUri":"%s"}]' $REPOSITORY_URI:master > imagedefinitions-web.json
      - printf '[{"name":"worker-task","imageUri":"%s"}]' $REPOSITORY_URI:master > imagedefinitions-worker.json
      - printf '[{"name":"dashboard-task","imageUri":"%s"}]' $REPOSITORY_URI:master > imagedefinitions-dashboard.json
      - cat imagedefinitions-*.json
artifacts:
    files:
      - imagedefinitions-web.json
      - imagedefinitions-worker.json
      - imagedefinitions-dashboard.json
