version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t asynchronous-tasks-image -f project/Dockerfile .
      - docker tag asynchronous-tasks-image:latest 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:latest
      - docker tag asynchronous-tasks-image:latest 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:latest
      - docker push 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master
      - echo Writing image definitions file...
      - printf '[{"name":"web-service","imageUri":"%s"}]' 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master > imagedefinitions.json
      - printf ',\n{"name":"worker-service","imageUri":"%s"}' 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master >> imagedefinitions.json
      - printf ',\n{"name":"dashboard-service","imageUri":"%s"}]' 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master >> imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files: imagedefinitions.json
