version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks-master
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:

      - echo Build started on `date`
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks .
      - docker tag 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:latest 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:$IMAGE_TAG
      - docker tag 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:latest 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:latest
      - docker push 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:$IMAGE_TAG
      - docker push 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' grovity-back-$ENVIRONMENT_NAME 235640865704.dkr.ecr.us-east-1.amazonaws.com/asynchronous-tasks:master > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json


