version: '3.8'

services:

  web:
    build:
      context: ./project
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: "web"
    ports:
      - 8004:8000
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build:
      context: ./project
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: "worker"
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7

  dashboard:
    build:
      context: ./project
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: "dashboard"
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
