version: '3.8'

services:

  web:
    image: 235640865704.dkr.ecr.us-east-1.amazonaws.com/web:latest
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    image: 235640865704.dkr.ecr.us-east-1.amazonaws.com/worker:latest
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7

  dashboard:
    image: 235640865704.dkr.ecr.us-east-1.amazonaws.com/dashboard:latest
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
